// <auto-generated />
using MSA.backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSA.backend.Api.Migrations
{
    [DbContext(typeof(WebAPIDBContext))]
    [Migration("20220806042952_createTable")]
    partial class createTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("MSA.backend.Api.Model.Move", b =>
                {
                    b.Property<string>("move")
                        .HasColumnType("TEXT");

                    b.HasKey("move");

                    b.ToTable("moves");
                });

            modelBuilder.Entity("MSA.backend.Model.pokemon", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ability")
                        .HasColumnType("TEXT");

                    b.Property<int>("weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("name");

                    b.ToTable("pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
